DROP TYPE IF EXISTS status;
CREATE TYPE status AS ENUM ('published','unpublished');

CREATE TABLE recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipename TEXT NOT NULL,
    experience TEXT,
    preptime TEXT,
    cooktime TEXT,
    servings TEXT,
    ingredients TEXT,
    directions TEXT,
    status status default 'unpublished'

);